services:
  compose-dashboard:
    image: "mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest"
    ports:
      - "18888"
    expose:
      - "18889"
      - "18890"
    networks:
      - "aspire"
    restart: "always"
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "my-rabbit-host" # Required to ensure data persistence matches the node name
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq # Mount point for RabbitMQ data
    networks:
      - "aspire"
  pricingsystem:
    image: "${PRICINGSYSTEM_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      # Give each one a UNIQUE port
      Kestrel__Certificates__Default__Password: "testpassword123456*!"
      Kestrel__Certificates__Default__Path: "/https/aspnetapp.pfx"
      Kestrel__Endpoints__GrpcApi__Url: "https://*:7001"
      Kestrel__Endpoints__RestApi__Url: "https://*:7250"
      Kestrel__Endpoints__http__Url: "https://*:8080"
      Kestrel__Endpoints__health-ep__Url: "http://*:8000"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://compose-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "PricingSystem"
    volumes:
      - /home/luke/aspnetapp.pfx:/https/aspnetapp.pfx:ro
    expose:
      - "7001"
      - "7250"
      - "8000"
      - "8080"
    networks:
      - "aspire"
  autotradesystem:
    image: "${AUTOTRADESYSTEM_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${AUTOTRADESYSTEM_PORT}"
      PRICINGSYSTEM_GRPCAPI: "https://pricingSystem:7001"
      PRICINGSYSTEM_RESTAPI: "https://pricingSystem:7250"
      PRICINGSYSTEM_HTTP: "http://pricingSystem:7001"
      PRICINGSYSTEM_HEALTH_EP: "http://pricingSystem:8000"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://compose-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "AutoTradeSystem"
      services__pricingsystem__http__0: "https://pricingsystem:8080"
      services__pricingsystem__https__0: "https://pricingsystem:8080"
      services__pricingsystem__grpc__0: "https://pricingsystem:7001"
      PricingSystemBaseURL: "https://pricingsystem:7001"
      ConnectionHostName: "${ConnectionHostName}"
      ConnectionStrings__my-rabbit: "${ConnectionStrings__my-rabbit}"
      ConnectionStrings__my_rabbit: "${ConnectionStrings__my-rabbit}"
      RabbitMQQueue: "${RabbitMQQueue}"
      RabbitMQExchange: "${RabbitMQExchange}"
    expose:
      - "${AUTOTRADESYSTEM_PORT}"
    depends_on:
      pricingsystem:
        condition: "service_started"
      rabbitmq:
        condition: "service_healthy"
    networks:
      - "aspire"
  tradeactionsystem:
    image: "${TRADEACTIONSYSTEM_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${TRADEACTIONSYSTEM_PORT}"
      PRICINGSYSTEM_GRPCAPI: "https://pricingSystem:7001"
      PRICINGSYSTEM_RESTAPI: "https://pricingSystem:7250"
      PRICINGSYSTEM_HTTP: "http://pricingSystem:7001"
      PRICINGSYSTEM_HEALTH_EP: "http://pricingSystem:8000"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://compose-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "TradeActionSystem"
      services__pricingsystem__http__0: "https://pricingsystem:8080"
      services__pricingsystem__https__0: "https://pricingsystem:8080"
      services__pricingsystem__grpc__0: "https://pricingsystem:7001"
      PricingSystemBaseURL: "https://pricingsystem:7001"
      ConnectionHostName: "${ConnectionHostName}"
      ConnectionStrings__my-rabbit: "${ConnectionStrings__my-rabbit}"
      ConnectionStrings__my_rabbit: "${ConnectionStrings__my-rabbit}"
      RabbitMQQueue: "${RabbitMQQueue}"
      RabbitMQExchange: "${RabbitMQExchange}"
    expose:
      - "${TRADEACTIONSYSTEM_PORT}"
    depends_on:
      pricingsystem:
        condition: "service_started"
      rabbitmq:
        condition: "service_healthy"
    networks:
      - "aspire"
networks:
  aspire:
    driver: "bridge"
volumes:
  rabbitmq_data:
    external: true
